## Copyright (C) 2021-2026 Advanced Micro Devices, Inc. All rights reserved. ##

### Shared Code #######################################################################################################
add_subdirectory(ddRpcShared)

### Client ############################################################################################################
add_subdirectory(ddRpcClient)

### Server ############################################################################################################
add_subdirectory(ddRpcServer)
