## Copyright (C) 2019-2026 Advanced Micro Devices, Inc. All rights reserved. ##

### Mercury Extension #################################################################################################
add_subdirectory(mercury)

### Command Extension #################################################################################################
add_subdirectory(command)
