//=============================================================================
/* Copyright (C) 2021-2026 Advanced Micro Devices, Inc. All rights reserved. */
/// @author AMD Developer Tools Team
/// @file
/// @brief Class implementation for emitting RMT page table update tokens.
//=============================================================================

#include "page_table_update_token_emitter.h"
#include "rmt_ftrace.h"

#include <util/rmtTokens.h>
#include <util/vector.h>

using namespace DevDriver;

namespace SystemTraceModule
{
    ////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
    PageTableUpdateTokenEmitter::PageTableUpdateTokenEmitter(IMsgChannel* msg_channel, AllocCb dd_alloc_cb, ModuleLogger& logger)
        : RMTTokenEmitter(msg_channel, logger)
        , dd_alloc_cb_(dd_alloc_cb)
    {
    }

    ////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
    PageTableUpdateTokenEmitter::~PageTableUpdateTokenEmitter()
    {
    }

    ////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
    DD_RESULT PageTableUpdateTokenEmitter::Initialize(DDEventProvider h_provider)
    {
        h_provider_ = h_provider;

        DD_RESULT result = ftrace_.Initialize();

        return result;
    }

    ////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
    void PageTableUpdateTokenEmitter::Cleanup()
    {
        ftrace_.Destroy();
    }

    DD_RESULT PageTableUpdateTokenEmitter::Enable()
    {
        ftrace_.Enable();
        return DD_RESULT_SUCCESS;
    }

    DD_RESULT PageTableUpdateTokenEmitter::Disable()
    {
        ftrace_.Disable();
        ResetTimer();
        return DD_RESULT_SUCCESS;
    }

    ////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
    DD_RESULT PageTableUpdateTokenEmitter::Emit()
    {
        DD_RESULT result = DD_RESULT_SUCCESS;

        rmt_ftrace::EventRecord record(ftrace_.PageTableUpdateEventFieldFormats(), dd_alloc_cb_);

        ftrace_.PollEvents(&record);

        if (record.is_new_event_polled)
        {
            result = ProcessAndEmit(record.ptu_events);
        }

        return result;
    }

    ////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
    DD_RESULT PageTableUpdateTokenEmitter::ProcessAndEmit(const DevDriver::Vector<rmt_ftrace::PageTableUpdateEvent, 128>& ptu_events)
    {
        const uint64_t FLAGS_VALID_MAPPING_MASK = 0x1;
        const uint64_t FLAGS_SYSMEM_MASK        = 0x2;

        // TODO: The timestamp isn't the time when the events are generated by kernel.
        uint8     delta  = 0;
        DD_RESULT result = CalculateTimeDelta(&delta);

        for (size_t i = 0; i < ptu_events.Size(); ++i)
        {
            const rmt_ftrace::PageTableUpdateEvent& page_table_update_event = ptu_events[i];
            if (page_table_update_event.valid)
            {
                // Emit kernel page table update event tokens.

                if (result == DD_RESULT_SUCCESS)
                {
                    const uint64 page_size = page_table_update_event.incr;

                    const uint32 process_id = static_cast<uint32>(page_table_update_event.pid);

                    const bool is_hbcc_mode = false;  // HBCC isn't currently supported on Linux.

                    bool is_unmap = false;
                    if ((page_table_update_event.flags & FLAGS_VALID_MAPPING_MASK) == 0x0)
                    {
                        is_unmap = true;
                    }

                    // There is no equivalent of transfer or discard for Linux memory
                    // management, so the type will always be set to UPDATE
                    const RMT_PAGE_TABLE_UPDATE_TYPE type = RMT_PAGE_TABLE_UPDATE_TYPE_UPDATE;

                    // Emit a single token with physical address set to zero, if the pages
                    // are mapped to the system memory or it's an unmap operatioin.
                    if (((page_table_update_event.flags & FLAGS_SYSMEM_MASK) == FLAGS_SYSMEM_MASK) || is_unmap)
                    {
                        RMT_MSG_PAGE_TABLE_UPDATE token(delta,
                                                        page_table_update_event.start,  // start of virtual address
                                                        0,                              // start of physical address
                                                        page_table_update_event.nptes,  // number of pages
                                                        GetRmtPageSize(page_size),
                                                        is_unmap,
                                                        process_id,
                                                        type,
                                                        is_hbcc_mode);

                        result = ddEventServerEmit(h_provider_, kRMTToken, token.Size(), token.Data());
                    }
                    // If the virtual pages are mapped to VRAM, iterate through contiguous
                    // physical pages and emit tokens.
                    else
                    {
                        rmt_ftrace::PageTableUpdatePhyAddrCoalesceIterator                    iter(page_table_update_event);
                        rmt_ftrace::PageTableUpdatePhyAddrCoalesceIterator::VirPhyAddressPair address_pair;

                        while (iter.Next(&address_pair))
                        {
                            RMT_MSG_PAGE_TABLE_UPDATE token(delta,
                                                            address_pair.virtual_address,
                                                            address_pair.physical_address,
                                                            address_pair.num_pages,
                                                            GetRmtPageSize(page_size),
                                                            is_unmap,
                                                            process_id,
                                                            type,
                                                            is_hbcc_mode);

                            result = ddEventServerEmit(h_provider_, kRMTToken, token.Size(), token.Data());
                            if (result != DD_RESULT_SUCCESS)
                            {
                                break;
                            }
                        }
                    }
                }
            }
        }

        return result;
    }

}
